accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
]

belle/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import QuickView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler400, handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index ,name='index'),
    path("short-description", views.description, name="short-description"),
    path("compare", views.compare, name="compare"),
    path('quickview/<int:pk>/', QuickView.as_view(), name='quickview'),
    path("test", views.test, name="test"),
]

handler404 = "belle.views.page_not_found_view" 
handler403 = 'belle.views.error_view'
handler400 = 'belle.views.permission_denied_view'
handler500 = 'belle.views.bad_request_view'

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    BlogView,
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    postpreference,
    # post_list
    )
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'blog'

urlpatterns = [
    path('', views.BlogView, name='home'),
    path('category/<str:name>', BlogListView.as_view(), name='blog-category'),
    path('blog/new/', BlogCreateView.as_view(), name='post-create'),
    # path('detail/<int:pk>/', views.BlogDetailView, name='post-detail'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='post-detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='post-update'),
    path('blog/<int:pk>/del/', BlogDeleteView.as_view(), name='post-delete'),
    path('blog/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']



accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

def signup_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()      
            # log the user in
            login(request, user)
            return redirect('/')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Account &ndash; Belle
{% endblock %}

{% block content %}
    
    <!--Body Content-->
    <div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Login</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 main-col offset-md-3">
                	<div class="mb-4">
                    <form method="POST" id="CustomerLoginForm" accept-charset="UTF-8" class="contact-form">
                      <div class="row">
                      {% csrf_token %}
                          
                          {{ form }}
                          
                      </div>
                      <p class="mb-4">
                                
                  <div class="row">
                    <div class="text-center col-12 col-sm-12 col-md-12 col-lg-12">
                        <input type="submit" class="btn mb-3" value="Sign In">
                        <p class="mb-4">
                    <a href="#" id="RecoverPassword">Forgot your password?</a> &nbsp; | &nbsp;
                      <a href="{% url 'accounts:signup' %}" id="customer_register_link">Create account</a>
                        </p>
                    </div>
                  </div>

                  </form>
                  </div>
               	</div>
            </div>
        </div>
        
    </div>
    <!--End Body Content-->
    
    {% endblock %}

templates/accounts/loginform.html
                       <form method="post" action="#" id="CustomerLoginForm" accept-charset="UTF-8" class="contact-form">	
                          <div class="row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="CustomerEmail">Email</label>
                                    <input type="email" name="customer[email]" placeholder="" id="CustomerEmail" class="" autocorrect="off" autocapitalize="off" autofocus="">
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="CustomerPassword">Password</label>
                                    <input type="password" value="" name="customer[password]" placeholder="" id="CustomerPassword" class="">                        	
                                </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="text-center col-12 col-sm-12 col-md-12 col-lg-12">
                                <input type="submit" class="btn mb-3" value="Sign In">
                                <p class="mb-4">
									<a href="#" id="RecoverPassword">Forgot your password?</a> &nbsp; | &nbsp;
								    <a href="register.html" id="customer_register_link">Create account</a>
                                </p>
                            </div>
                         </div>
                     </form>

templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Create an Account &ndash; Belle
{% endblock %}


{% block content %}
    
    <!--Body Content-->
    <div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Create an Account</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 main-col offset-md-3">
                	<div class="mb-4">
                        <form class="contact-form" action="{% url 'accounts:signup' %}" method="post" id="CustomerLoginForm" accept-charset="UTF-8" >	
                                {% csrf_token %}
                                {{ form }}

                          <div class="row">
                            <div class="text-center col-12 col-sm-12 col-md-12 col-lg-12">
                                <input type="submit" class="btn mb-3" value="Create">
                            </div>
                         </div>
                     </form>
                    </div>
               	</div>
            </div>
        </div>
        
    </div>
    <!--End Body Content-->
    {% endblock %}
    