belle/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import QuickView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler400, handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index ,name='index'),
    path("short-description", views.description, name="short-description"),
    path("compare", views.compare, name="compare"),
    path('quickview/<int:pk>/', QuickView.as_view(), name='quickview'),
    path("test", views.test, name="test"),
]

handler404 = "belle.views.page_not_found_view" 
handler403 = 'belle.views.error_view'
handler400 = 'belle.views.permission_denied_view'
handler500 = 'belle.views.bad_request_view'

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    BlogView,
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    postpreference,
    # post_list
    )
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'blog'

urlpatterns = [
    path('', views.BlogView, name='home'),
    path('category/<str:name>', BlogListView.as_view(), name='blog-category'),
    path('blog/new/', BlogCreateView.as_view(), name='post-create'),
    # path('detail/<int:pk>/', views.BlogDetailView, name='post-detail'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='post-detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='post-update'),
    path('blog/<int:pk>/del/', BlogDeleteView.as_view(), name='post-delete'),
    path('blog/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import (
    add_to_cart,
    CartView,
    delete_cart,
)

app_name = 'cart'

urlpatterns = [
    # path('add', views.add_to_cart, name='add_to_cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('delete/<slug>/', views.delete_cart, name='delete_cart'),
    path('update', views.update_cart, name='update_cart'),
    path('', views.CartView, name='home'),
]

pages/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'pages'

urlpatterns = [
    path('faqs/', views.faq_view, name='faqs'),
    path('about-us/', views.about_us_view, name='about-us'),
    path('contact-us/', views.contact_us_view, name='contact-us'),
    path('checkout/', views.checkout_view, name='checkout'),
    path("wishlist", views.wishlist, name="wishlist"),
]

blog/models.py
from distutils.command.upload import upload
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Blog(models.Model):
    images = models.ImageField(upload_to='blog_images', blank=True, null=True)
    title = models.CharField(max_length=10000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=1000)
    category = models.ForeignKey('BlogCategory', on_delete=models.CASCADE)
    # likes= models.IntegerField(default=0)
    # dislikes= models.IntegerField(default=0)
      
    # def __str__(self):
    #     return self.title

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post_connected=self).count()

    def get_image(self):
        if self.images and hasattr(self.images, 'url'):
            return self.images.url
        else:
            return 'path/to/default/image'

    def __str__(self):
        return self.title
    


class BlogCategory(models.Model):
    name = models.CharField(verbose_name='name', max_length=150)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child', on_delete=models.CASCADE)
    class Meta:
        unique_together = ('name', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])

class Comment(models.Model):
    content = models.TextField(max_length=150)
    email = models.EmailField(max_length=150)
    name = models.CharField(max_length=150)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_connected = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.post_connected.title


class Preference(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    post= models.ForeignKey(Blog, on_delete=models.CASCADE)
    value= models.IntegerField()
    date= models.DateTimeField(auto_now= True)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)

    class Meta:
       unique_together = ("user", "post", "value")



blog/forms.py
from django import forms
from .models import Comment


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            'name' : forms.TextInput(attrs={'placeholder':'name'}),
            'email' : forms.TextInput(attrs={}),
            'content' : forms.TextInput(attrs={})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Blog, Comment, Preference, BlogCategory
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from .forms import NewCommentForm
from django.contrib.auth.decorators import login_required

def is_users(post_user, logged_user):
    return post_user == logged_user

PAGINATION_COUNT = 3

# Create your views here.
@login_required(login_url='/accounts/login')
def BlogView(request):
    posts = Blog.objects.all().order_by('date_posted')
    recent_posts = posts[0:5]
    post_categories = BlogCategory.objects.all()

    return render(request, 'blog/home.html', {'posts':posts, 'post_categories': post_categories, 'recent_posts' : recent_posts})

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        posts = Blog.objects.all().order_by('date_posted')
        data = super().get_context_data(**kwargs)
        comments_connected = Comment.objects.filter(post_connected=self.get_object()).order_by('-date_posted')
        post_categories = BlogCategory.objects.all()
        data['comments'] = comments_connected
        data['form'] = NewCommentForm(instance=self.request.user)
        data['post_categories'] = post_categories
        data['recent_posts'] = posts[0:5]
        return data

    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content'),
                              author=self.request.user,
                              post_connected=self.get_object())
        new_comment.save()

        return self.get(self, request, *args, **kwargs)


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog
    template_name = 'blog/blog.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = PAGINATION_COUNT

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['preference'] = Preference.objects.all()
        return data


    def get_queryset(self):
        category = get_object_or_404(BlogCategory, name=self.kwargs.get('name'))
        return Blog.objects.filter(category=category)



class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    template_name = 'blog/post_delete.html'
    context_object_name = 'post'
    success_url = '/blog'

    def test_func(self):
        return is_users(self.get_object().author, self.request.user)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['title','description','code_snippet','github','download','images']
    template_name = 'blog/post_new.html'
    success_url = '/blog'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['tag_line'] = 'Add a new post'
        return data


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blog
    fields = ['title','description','code_snippet','github','download','images']
    template_name = 'blog/post_new.html'
    success_url = '/blog'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return is_users(self.get_object().author, self.request.user)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['tag_line'] = 'Edit a post'
        return data

# Like Functionality====================================================================================

@login_required
def postpreference(request, postid, userpreference):
        
        if request.method == "POST":
                eachpost= get_object_or_404(Blog, id=postid)

                obj=''

                valueobj=''

                try:
                        obj= Preference.objects.get(user= request.user, post= eachpost)

                        valueobj= obj.value #value of userpreference


                        valueobj= int(valueobj)

                        userpreference= int(userpreference)
                
                        if valueobj != userpreference:
                                obj.delete()


                                upref= Preference()
                                upref.user= request.user

                                upref.post= eachpost

                                upref.value= userpreference


                                if userpreference == 1 and valueobj != 1:
                                        eachpost.likes += 1
                                        eachpost.dislikes -=1
                                elif userpreference == 2 and valueobj != 2:
                                        eachpost.dislikes += 1
                                        eachpost.likes -= 1
                                

                                upref.save()

                                eachpost.save()
                        
                        
                                context= {'eachpost': eachpost,
                                  'postid': postid}

                                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))

                        elif valueobj == userpreference:
                                obj.delete()
                        
                                if userpreference == 1:
                                        eachpost.likes -= 1
                                elif userpreference == 2:
                                        eachpost.dislikes -= 1

                                eachpost.save()

                                context= {'eachpost': eachpost,
                                  'postid': postid}

                                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))
                                
                        
        
                
                except Preference.DoesNotExist:
                        upref= Preference()

                        upref.user= request.user

                        upref.post= eachpost

                        upref.value= userpreference

                        userpreference= int(userpreference)

                        if userpreference == 1:
                                eachpost.likes += 1
                        elif userpreference == 2:
                                eachpost.dislikes +=1

                        upref.save()

                        eachpost.save()                            


                        context= {'eachpost': eachpost,
                          'postid': postid}

                        return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))


        else:
                eachpost= get_object_or_404(Blog, id=postid)
                context= {'eachpost': eachpost,
                          'postid': postid}

                return HttpResponseRedirect(request.META.get('HTTP_REFERER',  '/'))

templates/blog/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Belle E-commerce Store - Blog
{% endblock %}
{% block minicart %}
<div class="col-4 col-sm-3 col-md-3 col-lg-2">
    <div class="site-cart">
        <a href="#;" class="site-header__cart" title="Cart">
            <i class="icon anm anm-bag-l"></i>
            <span id="CartCount" class="site-header__cart-count" data-cart-render="item_count">{{ forloop.counter }}</span>
        </a>
        <!--Minicart Popup-->
        <div id="header-cart" class="block block-cart">
            <ul class="mini-products-list">
                {% for cart in carts %}
                <li class="item">
                    <a class="product-image" href="#">
                        <img src="{{cart.item.get_image}}" alt="{{cart.item.title}}" title="{{cart.item.title}}" />
                    </a>
                    <div class="product-details">
                        <a href="{% url 'cart:delete_cart' cart.item.slug %}" class="remove"><i class="anm anm-times-l" aria-hidden="true"></i></a>
                        <a href="#" class="edit-i remove"><i class="anm anm-edit" aria-hidden="true"></i></a>
                        <a class="pName" href="{% url 'cart:home' %}">{{ cart.item.title  }}</a>
                        <div class="variant-cart">{{ cart.colour}} / {{ cart.size}}</div>
                        <div class="wrapQtyBtn">
                            <div class="qtyField">
                                <span class="label">Qty:</span>
                                <a class="qtyBtn minus" href="javascript:void(0);"><i class="fa anm anm-minus-r" aria-hidden="true"></i></a>
                                <input type="text" id="Quantity" name="quantity" value="{{cart.quantity}}" class="product-form__input qty">
                                <a class="qtyBtn plus" href="javascript:void(0);"><i class="fa anm anm-plus-r" aria-hidden="true"></i></a>
                            </div>
                        </div>
                        <div class="priceRow">
                            <div class="product-price">
                                <span class="money">$ {{cart.item.price}}</span>
                            </div>
                         </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="total">
                <div class="total-in">
                    <span class="label">Cart Subtotal:</span><span class="product-price"><span class="money">$</span></span>
                </div>
                 <div class="buttonSet text-center">
                    <a href="{% url 'cart:home' %}" class="btn btn-secondary btn--small">View Cart</a>
                    <a href="{% url 'pages:checkout' %}" class="btn btn-secondary btn--small">Checkout</a>
                </div>
            </div>
        </div>
        <!--End Minicart Popup-->
    </div>
    <div class="site-header__search">
        <button type="button" class="search-trigger"><i class="icon anm anm-search-l"></i></button>
    </div>
</div>
{% endblock %}


{% block content %}

    
    <!--Body Content-->
    <div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center mb-0">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Blog</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
	    <div class="bredcrumbWrap">
            <div class="container breadcrumbs">
                <a href="{% url 'index' %}" title="Back to the home page">Home</a><span aria-hidden="true">›</span>
            </div>
        </div>
        <div class="container">
        	<div class="row">
                <!--Main Content-->
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                	<div class="custom-search">
                        <form action="http://annimexweb.com/search" method="get" class="input-group search-header search" role="search" style="position: relative;">
                            <input class="search-header__input search__input input-group__field" type="search" name="q" placeholder="Search" aria-label="Search" autocomplete="off">
                            <span class="input-group__btn"><button class="btnSearch" type="submit"> <i class="icon anm anm-search-l"></i> </button></span>
                        </form>
                    </div>
                    <div class="blog--list-view blog--grid-load-more">
                        {% for post in posts %}
                    	<div class="article"> 
                            <!-- Article Image --> 
                             <a class="article_featured-image" href="{{post.images.url}}"><img class="blur-up lazyload" data-src="{{post.images.url}}" src="{{post.images.url}}" alt="{{ post.title }}"></a> 
                            <h2 class="h3"><a href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                            <ul class="publish-detail">                      
                                <li><i class="anm anm-user-al" aria-hidden="true"></i>   {{ post.author }}</li>
                                <li><i class="icon anm anm-clock-r"></i> <time datetime="{{ post.date_posted | date:"M d,  Y" }}">{{ post.date_posted | date:"M d,  Y" }}</time></li>
                                <li>
                                    <ul class="inline-list">   
                                        <li><i class="icon anm anm-comments-l"></i> <a href="#"> {{ post.number_of_comments }} comments</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="rte"> 
                                <p>{{post.description|truncatewords:80}}... </p>
                                 </div>
                            <p><a href="{% url 'blog:post-detail' post.id %}" class="btn btn-secondary btn--small">Read more <i class="fa fa-caret-right" aria-hidden="true"></i></a></p>
                        </div>
                        {% endfor %} 
                        <div class="loadmore-post">	
                            <a href="#;" class="btn loadMorepost">Load More</a>
                        </div>
                    </div>
                </div>
                <!--End Main Content-->
            </div>
        </div>
        
    </div>
    <!--End Body Content-->
    
    {% endblock %}