accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
]

belle/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import QuickView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from django.conf.urls import handler400, handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('', views.index ,name='index'),
    path("short-description", views.description, name="short-description"),
    path("compare", views.compare, name="compare"),
    path('quickview/<int:pk>/', QuickView.as_view(), name='quickview'),
    path("test", views.test, name="test"),
]

handler404 = "belle.views.page_not_found_view" 
handler403 = 'belle.views.error_view'
handler400 = 'belle.views.permission_denied_view'
handler500 = 'belle.views.bad_request_view'

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    BlogView,
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
    postpreference,
    # post_list
    )
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'blog'

urlpatterns = [
    path('', views.BlogView, name='home'),
    path('category/<str:name>', BlogListView.as_view(), name='blog-category'),
    path('blog/new/', BlogCreateView.as_view(), name='post-create'),
    # path('detail/<int:pk>/', views.BlogDetailView, name='post-detail'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='post-detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='post-update'),
    path('blog/<int:pk>/del/', BlogDeleteView.as_view(), name='post-delete'),
    path('blog/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import (
    add_to_cart,
    CartView,
    delete_cart,
)

app_name = 'cart'

urlpatterns = [
    # path('add', views.add_to_cart, name='add_to_cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('delete/<slug>/', views.delete_cart, name='delete_cart'),
    path('update', views.update_cart, name='update_cart'),
    path('', views.CartView, name='home'),
]

pages/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'pages'

urlpatterns = [
    path('faqs/', views.faq_view, name='faqs'),
    path('about-us/', views.about_us_view, name='about-us'),
    path('contact-us/', views.contact_us_view, name='contact-us'),
    path('checkout/', views.checkout_view, name='checkout'),
    path("wishlist", views.wishlist, name="wishlist"),
]

shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
]

templates/collection-tab.html
<!--Collection Tab slider-->
<div class="tab-slider-product section">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="section-header text-center">
                    <h2 class="h2">New Arrivals</h2>
                    <p>Browse the huge variety of our products</p>
                </div>
                <div class="tabs-listing">
                    <ul class="tabs clearfix">
                        <li class="active" rel="tab1">Women</li>
                        <li rel="tab2">Men</li>
                        <li rel="tab3">Sale</li>
                    </ul>

                    <div class="tab_container">
                        <div id="tab1" class="tab_content grid-products">
                            <div class="productSlider">
                                {% for item in items %}
                                <div class="col-12 item">
                                    <!-- start product image -->
                                    <div class="product-image">
                                        <!-- start product image -->
                                        <a href="{% url 'short-description' %}">
                                            <!-- image -->
                                            <img class="primary blur-up lazyload" data-src="{{ item.images.url }}" src="{{ item.images.url }}" alt="{{ item.name }}" title="{{ item.name }}">
                                            <!-- End image -->
                                            <!-- Hover image -->
                                            <img class="hover blur-up lazyload" data-src="{{ item.images1.url }}" src="{{ item.images1.url }}" alt="{{ item.name }}" title="{{ item.name }}">
                                            <!-- End hover image -->
                                            <!-- product label -->
                                            <div class="product-labels rectangular"><span class="lbl on-sale">{{ item.percent_save }}%</span> <span class="lbl pr-label1">new</span></div>
                                            <!-- End product label -->
                                        </a>
                                        <!-- end product image -->
                                        
                                        <!-- countdown start -->
                                        <div class="saleTime desktop" data-countdown="2022/03/01"></div>
                                        <!-- countdown end -->

                                        <!-- Start product button -->
                                        <form class="variants add" action="{% url 'cart:home' %}" onclick="window.location.href='{% url 'cart:home' %}'"method="post">
                                            <button class="btn btn-addto-cart" type="button" tabindex="0">Add To Cart</button>
                                        </form>
                                        <div class="button-set">
                                            <a href="javascript:void(0)" title="Quick View" class="quick-view-popup quick-view" data-toggle="modal" data-target="#content_quickview">
                                                <i class="icon anm anm-search-plus-r"></i>
                                            </a>
                                            <div class="wishlist-btn">
                                                <a class="wishlist add-to-wishlist" href="{% url 'pages:wishlist' %}">
                                                    <i class="icon anm anm-heart-l"></i>
                                                </a>
                                            </div>
                                            <div class="compare-btn">
                                                <a class="compare add-to-compare" href="{% url 'compare' %}" title="Add to Compare">
                                                    <i class="icon anm anm-random-r"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <!-- end product button -->
                                    </div>
                                    <!-- end product image -->
                                    <!--start product details -->
                                    <div class="product-details text-center">
                                        <!-- product name -->
                                        <div class="product-name">
                                            <a href="{% url 'short-description' %}">{{ item.title }}</a>
                                        </div>
                                        <!-- End product name -->
                                        <!-- product price -->
                                        <div class="product-price">
                                            <span class="old-price"></span>
                                            <span class="price"></span>
                                        </div>
                                        <!-- End product price -->
                                        
                                        <div class="product-review">
                                            
                                            <i class="font-13 fa fa-star"></i>
                                            
                                        </div>
                                        <!-- Variant -->
                                        <ul class="swatches">
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant1.jpg' %}" alt="image" /></li>
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant2.jpg' %}" alt="image" /></li>
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant3.jpg' %}" alt="image" /></li>
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant4.jpg' %}" alt="image" /></li>
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant5.jpg' %}" alt="image" /></li>
                                            <li class="swatch medium rounded"><img src="{% static 'images/product-images/variant6.jpg' %}" alt="image" /></li>
                                        </ul>
                                        <!-- End Variant -->
                                    </div>
                                    <!-- End product details -->
                                </div>
                                {% endfor %}
                                <div class="col-12 item">
                                    <!-- start product image -->
                                    <div class="product-image">
                                        <!-- start product image -->
                                        <a href="{% url 'short-description' %}">
                                            <!-- image -->
                                            <img class="primary blur-up lazyload" data-src="assets/images/product-images/product-image15.jpg" src="assets/images/product-images/product-image15.jpg" alt="image" title="product">
                                            <!-- End image -->
                                            <!-- Hover image -->
                                            <img class="hover blur-up lazyload" data-src="assets/images/product-images/product-image15-1.jpg" src="assets/images/product-images/product-image15-1.jpg" alt="image" title="product">
                                            <!-- End hover image -->
                                        </a>
                                        <!-- end product image -->

                                        <!-- Start product button -->
                                        <form class="variants add" action="#" onclick="window.location.href='{% url 'cart:home' %}'"method="post">
                                            <button class="btn btn-addto-cart" type="button" tabindex="0">Add To Cart</button>
                                        </form>
                                        <div class="button-set">
                                            <a href="javascript:void(0)" title="Quick View" class="quick-view-popup quick-view" data-toggle="modal" data-target="#content_quickview">
                                                <i class="icon anm anm-search-plus-r"></i>
                                            </a>
                                            <div class="wishlist-btn">
                                                <a class="wishlist add-to-wishlist" href="{% url 'pages:wishlist' %}">
                                                    <i class="icon anm anm-heart-l"></i>
                                                </a>
                                            </div>
                                            <div class="compare-btn">
                                                <a class="compare add-to-compare" href="{% url 'compare' %}" title="Add to Compare">
                                                    <i class="icon anm anm-random-r"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <!-- end product button -->
                                    </div>
                                    <!-- end product image -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>
<!--Collection Tab slider-->

templates/hello.html

index.html {% url 'index' %}
{% url 'accounts:logout' %}

faqs.html {% url 'pages:faq' %}
about-us.html {% url 'pages:about-us' %}
contact-us.html {% url 'pages:contact-us' %}
cart.html {% url 'cart:home' %}


templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Belle E-commerce Store -Index
{% endblock %}


{% block content %}
    
    <!--Body Content-->
    <div id="page-content">
    	<!--Home slider-->
    	<div class="slideshow slideshow-wrapper pb-section sliderFull">
        	<div class="home-slideshow">
            	<div class="slide">
                	<div class="blur-up lazyload bg-size">
                        <img class="blur-up lazyload bg-img" data-src="{% static 'images/slideshow-banners/belle-banner1.jpg' %}" src="{% static 'images/slideshow-banners/belle-banner1.jpg' %}" alt="Shop Our New Collection" title="Shop Our New Collection" />
                        <div class="slideshow__text-wrap slideshow__overlay classic bottom">
                            <div class="slideshow__text-content bottom">
                                <div class="wrap-caption center">
                                        <h2 class="h1 mega-title slideshow__title">Shop Our New Collection</h2>
                                        <span class="mega-subtitle slideshow__subtitle">From Hight to low, classic or modern. We have you covered</span>
                                    <a href="{% url 'shop:home' %}">
                                        <span class="btn">Shop now</span>
                                    </a>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="slide">
                	<div class="blur-up lazyload bg-size">
                        <img class="blur-up lazyload bg-img" data-src="{% static 'images/slideshow-banners/belle-banner2.jpg' %}" src="{% static 'images/slideshow-banners/belle-banner2.jpg' %}" alt="Summer Bikini Collection" title="Summer Bikini Collection" />
                        <div class="slideshow__text-wrap slideshow__overlay classic bottom">
                            <div class="slideshow__text-content bottom">
                                <div class="wrap-caption center">
                                    <h2 class="h1 mega-title slideshow__title">Summer Bikini Collection</h2>
                                    <span class="mega-subtitle slideshow__subtitle">Save up to 50% off this weekend only</span>
                                    <a href="{% url 'shop:home' %}">
                                        <span class="btn">Shop now</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--End Home slider-->
        





        
        <!--Collection Box slider-->
        <div class="collection-box section">
        	<div class="container-fluid">
				<div class="collection-grid">
                    {% for category in categories %}
                        <div class="collection-grid-item">
                            <a href="{{ category.images.url }}" class="collection-grid-item__link">
                                <img data-src="{{ category.get_image }}" src="{{ category.get_image }}" alt="{{ category.name }}" class="blur-up lazyload"/>
                                <div class="collection-grid-item__title-wrapper">
                                    <h3 class="collection-grid-item__title btn btn--secondary no-border">{{ category.name }}</h3>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                    </div>
            </div>
        </div>
        <!--End Collection Box slider-->
        
        <!--Logo Slider-->
        <div class="section logo-section">
        	<div class="container">
            	<div class="row">
                	<div class="col-12 col-sm-12 col-md-12 col-lg-12">
                		<div class="logo-bar">
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo1.png' %}" alt="" title="" />
                    </div>
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo2.png' %}" alt="" title="" />
                    </div>
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo3.png' %}" alt="" title="" />
                    </div>
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo4.png' %}" alt="" title="" />
                    </div>
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo5.png' %}" alt="" title="" />
                    </div>
                    <div class="logo-bar__item">
                        <img src="{% static 'images/logo/brandlogo6.png' %}" alt="" title="" />
                    </div>
                </div>
                	</div>
                </div>
            </div>
        </div>
        <!--End Logo Slider-->
        
        
        <!--Latest Blog-->
        <div class="latest-blog section pt-0">
        	<div class="container">
            	<div class="row">
                	<div class="col-12 col-sm-12 col-md-12 col-lg-12">
        				<div class="section-header text-center">
      						<h2 class="h2">Latest From our Blog</h2>
					    </div>
            		</div>
                </div>
            	<div class="row">
                    {% for recent_post in recent_posts %}
                	<div class="col-12 col-sm-12 col-md-6 col-lg-6">
                    	<div class="wrap-blog">
                        	<a href="{{ recent_post.images.url}}" class="article__grid-image">
              					<img src="{{ recent_post.images.url }}" alt="{{ recent_post.title }}" class="blur-up lazyloaded"/>
				            </a>
                            <div class="article__grid-meta article__grid-meta--has-image">
                                <div class="wrap-blog-inner">
                                    <h2 class="h3 article__title">
                                      <a href="{% url 'blog:post-detail' recent_post.id %}">{{ recent_post.title }}</a>
                                    </h2>
                                    <span class="article__date">{{ recent_post.date_posted | date:"M d,  Y" }}</span>
                                    <div class="rte article__grid-excerpt">
                                        {{recent_post.description|truncatewords:20}}...
                                    </div>
                                    <ul class="list--inline article__meta-buttons">
                                    	<li><a href="{% url 'blog:post-detail' recent_post.id %}">Read more</a></li>
                                    </ul>
                                    
                                </div>
							</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--End Latest Blog-->
        
        <!--Store Feature-->
        <div class="store-feature section">
        	<div class="container">
            	<div class="row">
                	<div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    	<ul class="display-table store-info">
                        	<li class="display-table-cell">
                            	<i class="icon anm anm-truck-l"></i>
                            	<h5>Free Shipping &amp; Return</h5>
                            	<span class="sub-text">Free shipping on all US orders</span>
                            </li>
                          	<li class="display-table-cell">
                            	<i class="icon anm anm-dollar-sign-r"></i>
                                <h5>Money Guarantee</h5>
                                <span class="sub-text">30 days money back guarantee</span>
                          	</li>
                          	<li class="display-table-cell">
                            	<i class="icon anm anm-comments-l"></i>
                                <h5>Online Support</h5>
                                <span class="sub-text">We support online 24/7 on day</span>
                            </li>
                          	<li class="display-table-cell">
                            	<i class="icon anm anm-credit-card-front-r"></i>
                                <h5>Secure Payments</h5>
                                <span class="sub-text">All payment are Secured and trusted.</span>
                        	</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!--End Store Feature-->
    </div>
    <!--End Body Content-->
    

        {% endblock %}
        